### ISSUE TITLE
Kodi not downloading 

### ISSUE THREAD

**Issue by tabby4661** [webosbrew/apps-repo#95] opened 2024-01-05 21:58 UTC
Can't download Kodi 
![IMG_20240106_032051](https://github.com/webosbrew/apps-repo/assets/62075094/f28c38a8-1a38-406c-b2a3-89f9c7dd20f4)

**Comment by throwaway96** [comment] 2024-01-09 02:32
Duplicate of #91.

**Closed by throwaway96** 2024-01-09 02:32 UTC
