### ISSUE TITLE
[IDEA] Stremio App

### ISSUE THREAD

**Issue by Heus-Sueh** [webosbrew/apps-repo#83] opened 2023-05-13 16:37 UTC
Please read conditions below carefully, and don't delete this part. Invalid issues will be closed.

* No apps related to piracy or intellectual property infringement is allowed.
* We can't guarantee if the app will be developed by anyone.
* We encourage you to develop the app by yourself. This would be a great contribution to webOS homebrew community.

- [x] I understand conditions above
- [ ] (Optional) I'd like to develop this app by myself

*Issue content starts below this line*

---

https://github.com/Stremio

**Comment by TulipVang** [comment] 2023-12-05 05:08
Any update on this

**Comment by throwaway96** [comment] 2023-12-06 01:46
To be honest I'm not sure exactly what people are asking to be ported. I took a look at Stremio a while ago, but I still don't really understand the architecture.

It might be possible to get the web interface working on webOS, but as far as I know nobody is working on it. The server is closed source. It could probably be made to work on webOS, but you'd have to ask the Stremio developers about that. You'd be better off asking them to port the web interface as well.

**Comment by kubo6472** [comment] 2023-12-23 12:49
How does one package a web app to run as an IPK? I have successfully setup their stremio/server docker image on a public URL and the web browser on my LG TV can kinda run it. I wonder if there exists a tool such as "MIT App Inventor" but for making IPKs?

**Comment by throwaway96** [comment] 2024-03-01 04:02
This was always kind of a weird request since Stremio is semi-proprietary commercial software, but the Stremio developers are working on a webOS port. No idea when/if it will be released (they will have to get it approved by LG), but you can take that up with them.

**Closed by throwaway96** 2024-03-01 04:02 UTC
Labels: idea

**Comment by ayushs-2k4** [comment] 2024-04-04 13:58
> This was always kind of a weird request since Stremio is semi-proprietary commercial software, but the Stremio developers are working on a webOS port. No idea when/if it will be released (they will have to get it approved by LG), but you can take that up with them.

Can you tell me where they stated that they are working on a webOS port or some progress forum?

**Comment by jaruba** [comment] 2024-05-01 22:19
Stremio is now available for LG TV in the app store: https://blog.stremio.com/stremio-is-now-available-on-lg-tvs-for-models-2020/

**Comment by jaruba** [comment] 2025-05-30 22:30
unfortunately not, the issue is that LG TV insists on censorship in those regions and Stremio cannot comply with strict censorship requirements
